DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS faculty_status;
DROP TABLE IF EXISTS faculty_point_info;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS scheduled_teaching;
DROP TABLE IF EXISTS exceptions;
DROP TABLE IF EXISTS rules;
DROP TABLE IF EXISTS logs;

CREATE TABLE users (
  user_id INTEGER PRIMARY KEY, -- AUTOINCREMENT
  user_name TEXT NOT NULL,
  user_email TEXT UNIQUE NOT NULL,
  user_ucinetid TEXT UNIQUE NOT NULL,
  admin INTEGER NOT NULL -- SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
);

CREATE TABLE faculty_status (
  user_id INTEGER,
  start_year INTEGER,
  end_year INTEGER,
  active_status INTEGER NOT NULL,
  role TEXT NOT NULL,
  PRIMARY KEY (user_id, start_year),
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE faculty_point_info (
  user_id INTEGER,
  year INTEGER,
  previous_balance REAL,
  ending_balance REAL,
  credit_due REAL,
  grad_count REAL,
  grad_students TEXT,
  PRIMARY KEY (user_id, year),
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE courses (
  course_id INTEGER PRIMARY KEY,  -- AUTOINCREMENT
  course_title_id TEXT UNIQUE NOT NULL,
  course_title TEXT NOT NULL,
  units INTEGER NOT NULL,
  course_level TEXT,
  combine_with TEXT
);

CREATE TABLE scheduled_teaching (
  user_id INTEGER,
  year INTEGER,
  quarter INTEGER,
  course_title_id TEXT,
  course_sec TEXT,
  enrollment INTEGER,
  offload_or_recall_flag INTEGER,
  teaching_point_val REAL,
  PRIMARY KEY (user_id, year, quarter, course_title_id, course_sec),
  FOREIGN KEY (user_id) REFERENCES users (user_id),
  FOREIGN KEY (course_title_id) REFERENCES courses (course_title_id)
);

CREATE TABLE exceptions (
  exception_id INTEGER PRIMARY KEY,  -- AUTOINCREMENT
  user_id INTEGER NOT NULL,
  year INTEGER NOT NULL,
  exception_category TEXT NOT NULL,
  message TEXT NOT NULL,
  points REAL,  
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE rules (
  rule_id INTEGER PRIMARY KEY, -- AUTOINCREMENT
  rule_name TEXT NOT NULL,
  value REAL
);

CREATE TABLE logs (
  log_id INTEGER PRIMARY KEY,  -- AUTOINCREMENT
  owner TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER,
  exception_id INTEGER,
  log_category TEXT,
  FOREIGN KEY (user_id) REFERENCES users (user_id),
  FOREIGN KEY (exception_id) REFERENCES exceptions (exception_id)
);


-- Initial rules and constant point values
INSERT INTO rules (rule_name, value)
VALUES
  ('Role-tenured research faculty', 3.5),
  ('Role-faculty up for tenure', 3.5),
  ('Role-assistant professor (1st year)', 1),
  ('Role-assistant professor (2nd+ year)', 2.5),
  ('Role-tenured POT', 6.5),
  ('Role-poT up for tenure', 6.5),
  ('Role-assistant POT (1st year)', 5),
  ('Role-assistant POT (2nd+ year)', 5.5),
  ('Category 0', 1.5),
  ('Category 1', 1.25),
  ('Category 2', 1),
  ('Category 3', 0.75),
  ('Category 4', 0.25);

-- Course Catalog
INSERT INTO courses (course_title_id, course_title, units, course_level, combine_with)
VALUES
  ('CS143B', 'PROJECT IN OPERATING SYSTEM ORGANIZATION', 4, 'Undergrad', null),
  ('ICS45C', 'PROGRAMMING IN C/C++ AS A SECOND LANGUAGE', 4, 'Undergrad', null),
  ('CS141', 'CONCEPTS IN PROGRAMMING LANGUAGES', 4, 'Undergrad', null),
  ('CS143A', 'LANGUAGE PROCESSOR CONSTRUCTION', 4, 'Undergrad', null),
  ('CS180A', 'SPECIAL TOPICS: PROJECT IN COMPUTER SCIENCE', 4, 'Undergrad', null),
  ('CS180B', 'SPECIAL TOPICS: PROJECT IN COMPUTER SCIENCE', 4, 'Undergrad', null),
  ('ICS5', 'ENVIRONMENTAL ISSUES IN INFORMATION TECHNOLOGY', 4, 'Undergrad', null),
  ('ICS6B', 'BOOLEAN ALGEBRA & LOGIC', 4, 'Undergrad', null),
  ('ICS6D', 'DISCRETE MATHEMATICS FOR COMPUTER SCIENCE', 4, 'Undergrad', null),
  ('ICS32', 'PROGRAMMING WITH SOFTWARE LIBRARIES', 4, 'Undergrad', null),
  ('ICS32A', 'PYTHN PGMG LIBR/ACC', 4, 'Undergrad', null),
  ('ICS60', 'COMPUTER GAMES & SOCIETY', 4, 'Undergrad', null),
  ('ICS139W', 'CRITICAL WRITING ON INFORMATION TECHNOLOGY', 4, 'Undergrad', null),
  ('CS103', 'ADVANCED PROGRAMMING & PROBLEM SOLVING WITH C++', 4, 'Undergrad', null),
  ('CS111', 'DIGITAL IMAGE PROCESSING', 4, 'Undergrad', null),
  ('CS112', 'COMPUTER GRAPHICS', 4, 'Undergrad', null),
  ('CS113', 'COMPUTER GAME DEVELOPMENT', 4, 'Undergrad', null),
  ('CS114', 'PROJECTS IN ADVANCED 3D COMPUTER GRAPHICS', 4, 'Undergrad', null),
  ('CS115', 'COMPUTER SIMULATION', 4, 'Undergrad', null),
  ('CS116', 'COMPUTATIONAL PHOTOGRAPHY & VISION', 4, 'Undergrad', null),
  ('CS117', 'PROJECT IN COMPUTER VISION', 4, 'Undergrad', null),
  ('CS118', 'INTRODUCTION TO VR', 4, 'Undergrad', null),
  ('CS121', 'INFORMATION RETRIEVAL', 4, 'Undergrad', null),
  ('CS122A', 'INTRODUCTION TO DATA MANAGEMENT', 4, 'Undergrad', null),
  ('CS122B', 'PROJECT IN DATABASES & WEB APPLICATIONS', 4, 'Undergrad', null),
  ('CS122C', 'PRINCIPLES OF DATA MANAGEMENT', 4, 'Undergrad', null),
  ('CS122D', 'BEYOND SQL DATA MANAGEMENT', 4, 'Undergrad', null),
  ('CS125', 'NEXT GENERATION SEARCH SYSTEMS', 4, 'Undergrad', null),
  ('CS131', 'PARELLEL & DISTRIBUTED COMPUTING', 4, 'Undergrad', null),
  ('CS132', 'COMPUTER NETWORKS', 4, 'Undergrad', null),
  ('CS133', 'ADVANCED COMPUTER NETWORKS', 4, 'Undergrad', null),
  ('CS134', 'COMPUTER & NETWORK SECURITY', 4, 'Undergrad', null),
  ('CS137', 'INTERNET APPLICATIONS ENGINEERING', 4, 'Undergrad', null),
  ('CS142A', 'COMPILERS & INTERPRETERS', 4, 'Undergrad', null),
  ('CS142B', 'PRINCICPLES OF OPERATING SYSTEMS', 4, 'Undergrad', null),
  ('CS145', 'EMBEDDED SOFTWARE', 4, 'Undergrad', null),
  ('CS145L', 'EMBEDDED SOFTWARE LABORATORY', 2, 'Undergrad', null),
  ('CS146', 'PROGRAMMING IN MULTITASKING OPERATING SYSTEMS', 4, 'Undergrad', null),
  ('CS147', 'IOT SOFTWARE & SYSTEMS', 4, 'Undergrad', null),
  ('CS151', 'DIGITAL LOGIC DESIGN', 4, 'Undergrad', null),
  ('CS152', 'COMPUTER SYSTEMS ARCHITECTURE', 4, 'Undergrad', null),
  ('CS153', 'LOGIC DESIGN LABORATORY', 4, 'Undergrad', null),
  ('CS154', 'COMPUTER DESIGN LABORATORY', 4, 'Undergrad', null),
  ('CS161', 'DESIGN & ANALYSIS OF ALGORITHMS', 4, 'Undergrad', null),
  ('CS162', 'FORMAL LANGUAGES & AUTOMATA', 4, 'Undergrad', null),
  ('CS163', 'GRAPH ALGORITHMS', 4, 'Undergrad', 'CS265'),
  ('CS164', 'COMPUTATIONAL GEOMETRY & GEOMETRIC MODELING', 4, 'Undergrad', null),
  ('CS165', 'PROJECT IN ALGORITHMS & DATA STRUCTURES', 4, 'Undergrad', null),
  ('CS166', 'QUANTUM COMPUTATION & INFORMATION', 4, 'Undergrad', null),
  ('CS167', 'INTRODUCTION TO APPLIED CRYPTOGRAPHY', 4, 'Undergrad', null),
  ('CS169', 'INTRODUCTION TO OPTIMIZATION', 4, 'Undergrad', null),
  ('CS171', 'INTRODUCTION TO ARTIFICIAL INTELLIGENCE', 4, 'Undergrad', null),
  ('CS172B', 'NEURAL NETWORKS & DEEP LEARNING', 4, 'Undergrad', null),
  ('CS172C', 'ARTIFICIAL INTELLIGENCE FRONTIERS: TECHNICAL, ETHICAL, AND SOCIETAL', 4, 'Undergrad', null),
  ('CS175', 'PROJECT IN ARTIFICIAL INTELLIGENCE', 4, 'Undergrad', null),
  ('CS177', 'APPLICATION OF PROBABILITY IN COMPUTER SCIENCE', 4, 'Undergrad', null),
  ('CS178', 'MACHINE LEARNING & DATA-MINING', 4, 'Undergrad', null),
  ('CS179', 'ALGORITHMS FOR PROBABILISTIC & DETERMINISTIC GRAPHICAL MODELS', 4, 'Undergrad', null),
  ('CS183', 'INTRODUCTION TO COMPUTATIONAL BIOLOGY', 4, 'Undergrad', null),
  ('CS184A', 'REPRESENTATIONS & ALGORITHMS FOR MOLECULAR BIOLOGY', 4, 'Undergrad', null),
  ('CS184C', 'COMPUTATIONAL SYSTEMS BIOLOGY', 4, 'Undergrad', null),
  ('CS189', 'PROJECT IN BIOINFORMATICS', 4, 'Undergrad', null),
  ('CS190', 'SPECIAL TOPICS IN INFORMATION & COMPUTER SCIENCE', 4, 'Undergrad', null),
  ('CS200S', 'SEMINAR IN COMPUTER SCIENCE RESEARCH', 1, 'Grad', null),
  ('CS201', 'FOUNDATIONS OF CRYPTOGRAPHIC PROTOCOLS', 4, 'Grad', null),
  ('CS202', 'APPLIED CRYPTOGRAPHY', 4, 'Grad', null),
  ('CS203', 'NETWORK & DISTRIBUTED SYSTEMS SECURITY', 4, 'Grad', null),
  ('CS204', 'USABLE SECURITY & PRIVACY', 4, 'Grad', null),
  ('CS205', 'COMPUTER SYSTEMS SECURITY', 4, 'Grad', null),
  ('CS206', 'PRINCIPLES OF SCIENTIFIC COMPUTING', 4, 'Grad', null),
  ('CS211A', 'VISUAL COMPUTING', 4, 'Grad', null),
  ('CS211B', 'ADVANCED TOPICS IN 3D COMPUTER GRAPHICS', 4, 'Grad', null),
  ('CS211C', 'NEW COURSE', 4, 'Grad', null),
  ('CS212', 'MULTIMEDIA SYSTEMS & APPLICATIONS', 4, 'Grad', null),
  ('CS213', 'INTRODUCTION TO VISUAL PERCEPTION', 4, 'Grad', null),
  ('CS216', 'IMAGE UNDERSTANDING', 4, 'Grad', null),
  ('CS217', 'LIGHT & GEOMETRY IN COMPUTER VISION', 4, 'Grad', null),
  ('CS219S', 'SEMINOR IN GRPHICS', 2, 'Grad', null),
  ('CS221', 'INFORMATION RETRIEVAL, FILTERING, & CLASSIFICATION', 4, 'Grad', null),
  ('CS222', 'PRINCICPLES OF DATA MANAGEMENT', 4, 'Grad', null),
  ('CS223', 'TRANSACTION PROCESSING & DISTRIBUTED DATA MANAGEMENT', 4, 'Grad', null),
  ('CS224', 'TOPICS IN ADVANCED DATA MANAGEMENT', 4, 'Grad', null),
  ('CS225', 'NEXT GENERATION SEARCH SYSTEMS', 4, 'Grad', null),
  ('CS230', 'DISTRIBUTED COMPUTER SYSTEMS', 4, 'Grad', null),
  ('CS232', 'COMPUTER & COMMUNICATION NETWORKS', 4, 'Grad', null),
  ('CS233', 'NETWORKING LABORATORY', 4, 'Grad', null),
  ('CS234', 'ADVANCED NETWORKS', 4, 'Grad', null),
  ('CS236', 'WIRELESS & MOBILE NETWORKING', 4, 'Grad', null),
  ('CS237', 'MIDDLEWARE FOR NETWORKED & DISTRIBUTED SYSTEMS', 4, 'Grad', null),
  ('CS238', 'ADVANCED OPERATING SYSTEMS', 4, 'Grad', null),
  ('CS241', 'ADVANCED COMPILER CONSTRUCTION', 4, 'Grad', null),
  ('CS242', 'PARALLEL COMPUTING', 4, 'Grad', null),
  ('CS243', 'HIGH-PERFORMANCE ARCHITECTURE & THEIR COMPILERS', 4, 'Grad', null),
  ('CS244', 'INTRODUCTION TO EMBEDDED & UBIQUITOUS SYSTEMS', 4, 'Grad', null),
  ('CS245', 'SOFTWARE FOR EMBEDDED SYSTEMS', 4, 'Grad', null),
  ('CS247', 'COMPLEX SYSTEMS SOFTWARE', 4, 'Grad', null),
  ('CS248A', 'INTRODUCTION TO UBIQUITOUS COMPUTING', 4, 'Grad', null),
  ('CS248B', 'UBIQUITOUS COMPUTING & INTERACTION', 4, 'Grad', null),
  ('CS250A', 'COMPUTER SYSTEMS ARCHITECTURE', 4, 'Grad', null),
  ('CS250B', 'MODERN COMPUTER SYSTEMS', 4, 'Grad', null),
  ('CS252', 'INTRODUCTION TO COMPUTER DESIGN', 4, 'Grad', null),
  ('CS253', 'ANALYSIS OF PROGRAMMING LANGUAGES', 4, 'Grad', null),
  ('CS259S', 'SEMINAR IN DESIGN SCIENCE', 2, 'Grad', null),
  ('CS260', 'FUNDAMENTALS OF THE DESIGN & ANALYSIS OF ALGORITHMS', 4, 'Grad', null),
  ('CS261', 'DATA STRUCTURES', 4, 'Grad', null),
  ('CS262', 'COMPUTATIONAL COMPLEXITY', 4, 'Grad', null),
  ('CS263', 'ANALYSIS OF ALGORITHMS', 4, 'Grad', null),
  ('CS264', 'QUANTUM COMPUTATION & INFORMATION', 4, 'Grad', null),
  ('CS265', 'GRAPH ALGORITHMS', 4, 'Grad', 'CS163'),
  ('CS266', 'COMPUTATIONAL GEOMETRY', 4, 'Grad', null),
  ('CS268', 'INTRODUCTION TO OPTIMIZATION', 4, 'Grad', null),
  ('CS269S', 'SEMINAR IN THE THEORY OF ALGORITHMS & DATA STRUCTURES', 2, 'Grad', null),
  ('CS271', 'INTRODUCTION TO ARTIFICIAL INTELLIGENCE', 4, 'Grad', null),
  ('CS272', 'STATISTICAL NATURAL LANGUAGE PROCESSING', 4, 'Grad', null),
  ('CS273A', 'MACHINE LEARNING', 4, 'Grad', null),
  ('CS274A', 'PROBABILISTIC LEARNING: THEORY & ALGORITHMS', 4, 'Grad', null),
  ('CS274B', 'LEARNING IN GRAPHICAL MODELS', 4, 'Grad', null),
  ('CS274C', 'NEURAL NETWORKS & DEEP LEARNING', 4, 'Grad', null),
  ('CS274D', 'ARTIFICIAL INTELLIGENCE FRONTIERS: TECHNICAL, ETHICAL, AND SOCIETAL', 4, 'Grad', null),
  ('CS274E', 'DEEP GENERATIVE MODELS', 4, 'Grad', null),
  ('CS275', 'NETWORK-BASED REASONING/ CONSTRAINT NETWORKS', 4, 'Grad', null),
  ('CS276', 'NETWORK-BASED REASONING/ BELIEF NETWORKS', 4, 'Grad', null),
  ('CS277', 'CONTROL AND REINFORCEMENT LEARNING', 4, 'Grad', null),
  ('CS278', 'PROBABILITY MODELS', 4, 'Grad', null),
  ('CS284A', 'REPRESENTATIONS & ALGORITHMS FOR MOLECULAR BIOLOGY', 4, 'Grad', null),
  ('CS284C', 'COMPUTATIONAL SYSTEMS BIOLOGY', 4, 'Grad', null),
  ('CS285', 'MATHEMATICAL & COMPUTATIONAL BIOLOGY', 4, 'Grad', null),
  ('CS290', 'RESEARCH SEMINAR', 2, 'Grad', null),
  ('CS295', 'SPECIAL TOPICS', 4, 'Grad', null),
  ('CS296', 'ELEMENTS OF SCIENTIFIC WRITING', 4, 'Grad', null),
  ('CS201P', 'INTRO TO COMPUTER SECURITY', 4, 'Grad', null),
  ('CS202P', 'APPLIED CRYPTOGRAPHY', 4, 'Grad', null),
  ('CS203P', 'NETWORK & DISTRIBUTED SYSTEMS SECURITY', 4, 'Grad', null),
  ('CS206P', 'PRINCIPLES OF SCIENTIFIC COMPUTING', 4, 'Grad', null),
  ('CS210P', 'COMPUTER GRAPHICS & VISUALIZATION', 4, 'Grad', null),
  ('CS211P', 'VISUAL COMPUTING', 4, 'Grad', null),
  ('CS220P', 'DATABASES & DATA MANAGEMENT', 4, 'Grad', null),
  ('CS222P', 'PRINCICPLES OF DATA MANAGEMENT', 4, 'Grad', null),
  ('CS223P', 'TRANSACTION PROCESSING & DIST. DATA MGMT', 4, 'Grad', null),
  ('CS224P', 'BIG DATA MANAGEMENT', 4, 'Grad', null),
  ('CS230P', 'DISTRIBUTED COMPUTER SYSTEMS', 4, 'Grad', null),
  ('CS231P', 'PARALLEL AND DISTRIBUTED COMPUTING FOR PROFESSIONALS', 4, 'Grad', null),
  ('CS232P', 'COMPUTER & COMMUNICATION NETWORKS', 4, 'Grad', null),
  ('CS238P', 'OPERATING SYSTEMS', 4, 'Grad', null),
  ('CS242P', 'COMPILERS & INTERPRETERS', 4, 'Grad', null),
  ('CS244P', 'INTRODUCTION TO EMBEDDED & UBIQUITOUS SYSTEMS', 4, 'Grad', null),
  ('CS250P', 'COMPUTER SYSTEMS ARCHITECTURE', 4, 'Grad', null),
  ('CS253P', 'ADVANCED PROGRAMMING & PROBLEM SOLVING', 4, 'Grad', null),
  ('CS260P', 'FUNDAMENTALS OF ALGORITHMS WITH APPLICATIONS', 4, 'Grad', null),
  ('CS261P', 'DATA STRUCTURES', 4, 'Grad', null),
  ('CS262P', 'AUTOMATA & GRAMMARS', 4, 'Grad', null),
  ('CS267P', 'DATA COMPRESSION', 4, 'Grad', null),
  ('CS268P', 'INTRODUCTION TO OPTIMIZATION', 4, 'Grad', null),
  ('CS271P', 'INTRODUCTION TO ARTIFICIAL INTELLIGENCE', 4, 'Grad', null),
  ('CS273P', 'MACHINE LEARNING', 4, 'Grad', null),
  ('CS274P', 'NEURAL NETWORKS & DEEP LEARNING', 4, 'Grad', null),
  ('CS275P', 'GRAPHICAL MODELS & STATISTICAL LEARNING', 4, 'Grad', null),
  ('CS294P', 'KEYSTONE COMMUNICATION', 4, 'Grad', null),
  ('CS295P', 'KEYSTONE PROJECT', 4, 'Grad', null),
  ('CS296P', 'CAPSTONE PROFESSIONAL WRITING FOR COMPUTER SCIENCE CAREERS', 4, 'Grad', null),
  ('CS297P', 'CAPSTONE DESIGN PROJECT FOR COMPUTER SCIENCE', 4, 'Grad', null),
  ('CS298P', 'THESIS SUPERVISION', 2, 'Grad', null),
  ('CS299P', 'INDIVIDUAL STUDY', 2, 'Grad', null),
  ('CSE90', 'SYSTEMS ENGINEERING ETHICS & TECHNICAL COMMUNICATIONS', 2, 'Undergrad', null),
  ('ICS3', 'INTERNET TECHNOLOGIES & THEIR SOCIAL IMPACT', 4, 'Undergrad', null),
  ('ICS4', 'HUMAN FACTORS FOR THE WEB', 4, 'Undergrad', null),
  ('ICS6N', 'COMPUTATIONAL LINEAR ALGEBRA', 4, 'Undergrad', null),
  ('ICS7', 'INTRODUCING MODERN COMPUTATIONAL TOOLS', 4, 'Undergrad', null),
  ('ICS9', 'Intro to Computation for Scientists and Engineers', 4, 'Undergrad', null),
  ('ICS10', 'HOW COMPUTERS WORK', 4, 'Undergrad', null),
  ('ICS11', 'THE INTERNET & PUBLIC POLICY', 4, 'Undergrad', null),
  ('ICS20', 'INVITATION TO COMPUTING', 4, 'Undergrad', null),
  ('ICS31', 'INTRODUCTION TO PROGRAMMING', 4, 'Undergrad', null),
  ('ICS33', 'INTERMEDIATE PROGRAMMING', 4, 'Undergrad', null),
  ('ICS45J', 'PROGRAMMING IN JAVA AS A SECOND LANGUAGE', 4, 'Undergrad', null),
  ('ICS46', 'DATA STRUCTURE IMPLEMENTATION & ANALYSIS', 4, 'Undergrad', null),
  ('ICS51', 'INTRODUCTORY COMPUTER ORGANIZATION', 6, 'Undergrad', null),
  ('ICS53', 'PRINCIPLES IN SYSTEM DESIGN', 4, 'Undergrad', null),
  ('ICS53L', 'PRINCIPLES IN SYSTEM DESIGN LIBRARY', 2, 'Undergrad', null),
  ('ICS61', 'GAME SYSTEMS & DESIGN', 4, 'Undergrad', null),
  ('ICS62', 'GAME TECHNOLOGIES & INTERACTIVE MEDIA', 4, 'Undergrad', null),
  ('ICS80', 'ENTREPRENEURSHIP', 2, 'Undergrad', null),
  ('ICS90', 'NEW STUDENTS SEMINAR', 1, 'Undergrad', null),
  ('ICS161', 'GAME ENGINE LAB', 4, 'Undergrad', null),
  ('ICS162', 'MODELING & WORLD BUILDING', 4, 'Undergrad', null),
  ('ICS163', 'MOBILE & UBIQUITOUS GAMES', 4, 'Undergrad', null),
  ('ICS166', 'GAME DESIGN', 4, 'Undergrad', null),
  ('ICS167', 'MULTIPLAYER GAME SYSTEMS', 4, 'Undergrad', null),
  ('ICS168', 'MULTIPLAYER GAME PROJECT', 4, 'Undergrad', null),
  ('ICS169A', 'CAPSTONE GAME PROJECT I', 4, 'Undergrad', null),
  ('ICS169B', 'CAPSTONE GAME PROJECT II', 4, 'Undergrad', null),
  ('ICS192', 'INDUSTRIAL OR PUBLIC SECTOR FIELD STUDY', 2, 'Undergrad', null),
  ('ICS193', 'TUTORING IN ICS', 2, 'Undergrad', null),
  ('ICSH197', 'HONORS SEMINAR', 2, 'Undergrad', null),
  ('ICS290', 'ENTREPRENEURSHIP', 4, 'Grad', null),
  ('ICS398A', 'TEACHING ASSISTANT TRAINING SEMINAR', 2, 'Grad', null),
  ('ICS398B', 'ADVANCED TEACHING ASSISTANT SEMINAR', 4, 'Grad', null),
  ('ICS399', 'UNIVERSITY TEACHING', 4, 'Grad', null);
